FROM node:20-bookworm

WORKDIR /file-server

COPY ./file-server .

RUN npm install

RUN npm run gen

RUN npm run build

ARG DEFAULT_PORT=8000

ENV PORT $DEFAULT_PORT

EXPOSE $PORT

CMD ["npm", "run", "start:prod"]