version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - main-backend
  main-backend:
    build:
      context: .
      dockerfile: ./main-backend/dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./main-backend:/main-backend
    depends_on:
      - db
      - file-server
  file-server:
    build:
      context: .
      dockerfile: ./file-server/dockerfile
    ports:
      - '8001:8000'
    volumes:
      - ./file-server:/file-server
  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5499:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
