version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: ./frontend/dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - main-backend-dev
  main-backend-dev:
    build:
      context: .
      dockerfile: ./main-backend/dockerfile.dev
    ports:
      - '8000:8000'
    volumes:
      - ./main-backend:/main-backend
    depends_on:
      - db-dev
      - file-server-dev
  file-server-dev:
    build:
      context: .
      dockerfile: ./file-server/dockerfile.dev
    ports:
      - '8001:8000'
    volumes:
      - ./file-server:/file-server
  db-dev:
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5499:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
