version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/dockerfile.prod
    image: hampushampus/gallery:frontend
    ports:
      - '5173:5173'
    depends_on:
      - main-backend
  main-backend:
    build:
      context: .
      dockerfile: ./main-backend/dockerfile.prod
    image: hampushampus/gallery:main-backend
    ports:
      - '8000:8000'
    depends_on:
      - db
      - file-server
  file-server:
    build:
      context: .
      dockerfile: ./file-server/dockerfile.prod
    image: hampushampus/gallery:file-server
    ports:
      - '8001:8000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5499:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
