version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - main-backend
  main-backend:
    build:
      context: .
      dockerfile: ./main-backend/dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./main-backend:/main-backend:ro
    depends_on:
      - db
      - file-store
  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5499:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
  file-store:
    build:
      context: .
      dockerfile: ./file-store/dockerfile
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./file-store/data:/data
